const TRACK_DEVOPS = {
    id: "devops", code: "DEVOPS", title: "DevOps",
    tagline: "From source to production.",
    blurb: "The path from your first commit to a deploy you trust at 3am — pipelines, containers, infra, observability.",
    storageKey: "ops4life:devops", accent: "var(--c-teal)",
    sections: [
      { id:"foundations", title:"01 · Foundations", color:"var(--c-purple)", items: [
        { id:"linux",    label:"Linux & shell",        type:"recommended", concepts:["filesystem","permissions","systemd","networking"], tools:["bash","zsh","tmux"],
          description:"Linux is the foundation of almost every server, container, and cloud instance. Deep Linux knowledge separates good DevOps engineers from great ones.",
          resources:[{kind:"read",label:"The Linux Command Line (free book)",url:"https://linuxcommand.org/tlcl.php"},{kind:"read",label:"Linux Journey",url:"https://linuxjourney.com/"}],
          tip:"Practice on a real VM. Theoretical knowledge is useless without muscle memory from breaking and fixing real systems." },
        { id:"git",      label:"Git workflows",        type:"recommended", concepts:["branching","rebase","tags","hooks"], tools:["git","gh"],
          description:"Git is non-negotiable. Master branching strategies, rebasing, and the internals of how Git stores objects — it makes debugging merge conflicts trivial.",
          resources:[{kind:"read",label:"Pro Git (free book)",url:"https://git-scm.com/book"},{kind:"interactive",label:"Learn Git Branching",url:"https://learngitbranching.js.org/"}],
          tip:"`git reflog` is your safety net. It records every HEAD movement, so you can recover from almost any mistake if you act quickly." },
        { id:"http",     label:"HTTP & APIs",          type:"recommended", concepts:["REST","status codes","headers","TLS"], tools:["curl","httpie"],
          description:"HTTP is the lingua franca of distributed systems. Understanding request/response semantics, status codes, and headers is essential for debugging microservices.",
          resources:[{kind:"read",label:"MDN HTTP docs",url:"https://developer.mozilla.org/en-US/docs/Web/HTTP"},{kind:"read",label:"HTTP/2 explained",url:"https://http2-explained.haxx.se/"}],
          tip:"`curl -v` shows the full TLS handshake and HTTP headers. It's the most useful debugging tool you'll reach for every day." },
        { id:"editor",   label:"Pick a code editor",   type:"alt",         concepts:["LSP","extensions"], tools:["vscode","neovim"],
          description:"Your editor is where you spend most of your day. Invest time in mastering it — shortcuts, LSP integration, and plugins compound into hours saved per week." },
      ]},
      { id:"automation", title:"02 · Automation", color:"var(--c-teal)", items: [
        { id:"ci",       label:"CI fundamentals",      type:"recommended", concepts:["pipelines","artifacts","cache","matrix"], tools:["GitHub Actions","GitLab CI"],
          description:"Continuous integration catches bugs before they reach production. A good CI pipeline runs fast, fails loudly, and gives developers confidence to ship.",
          resources:[{kind:"docs",label:"GitHub Actions docs",url:"https://docs.github.com/en/actions"},{kind:"docs",label:"GitLab CI docs",url:"https://docs.gitlab.com/ee/ci/"}],
          tip:"Invest in pipeline caching early. A 10-minute pipeline that could be 2 minutes destroys developer flow and trust in CI." },
        { id:"cd",       label:"Continuous delivery",  type:"recommended", concepts:["envs","promotion","rollbacks"], tools:["Argo CD","Flux"],
          description:"Continuous delivery makes releasing software a non-event. GitOps tools like Argo CD let you declare desired state in Git and let controllers reconcile reality.",
          resources:[{kind:"docs",label:"Argo CD docs",url:"https://argo-cd.readthedocs.io/"},{kind:"read",label:"GitOps principles",url:"https://opengitops.dev/"}],
          tip:"Make rollbacks boring. If rolling back is a manual, scary procedure, your CD pipeline isn't done yet." },
        { id:"testing",  label:"Test in pipelines",    type:"recommended", concepts:["unit","integration","e2e","flake"], tools:["jest","pytest","playwright"],
          description:"Tests in CI are only valuable if they're fast and trustworthy. Flaky tests are worse than no tests — they erode trust and get ignored.",
          tip:"Quarantine flaky tests immediately. A flaky test that's ignored teaches everyone to ignore all test failures." },
        { id:"scripting",label:"Scripting glue",       type:"alt",         concepts:["idempotence","retries"], tools:["bash","python","make"],
          description:"Translate repetitive manual tasks into scripts. Good DevOps engineers automate everything that happens more than twice.",
          tip:"Write idempotent scripts — running them twice should produce the same result as running them once. This is the difference between a script and a reliable tool." },
      ]},
      { id:"infra", title:"03 · Infra", color:"var(--c-orange)", items: [
        { id:"docker",   label:"Containers",           type:"recommended", concepts:["images","layers","networking","volumes"], tools:["docker","podman"],
          description:"Containers are the unit of deployment for modern software. Understanding image layers, networking, and volumes lets you build efficient, reproducible environments.",
          resources:[{kind:"docs",label:"Docker docs",url:"https://docs.docker.com/"},{kind:"read",label:"Docker deep dive",url:"https://www.manning.com/books/docker-deep-dive"}],
          tip:"Keep images small. Multi-stage builds and distroless base images drastically cut attack surface and pull times." },
        { id:"k8s",      label:"Kubernetes basics",    type:"recommended", concepts:["pods","deployments","services","ingress"], tools:["kubectl","helm"],
          description:"Kubernetes is the operating system of the cloud. Learn the primitives deeply — Pods, Deployments, Services, ConfigMaps — before reaching for higher-level abstractions.",
          resources:[{kind:"docs",label:"Kubernetes docs",url:"https://kubernetes.io/docs/"},{kind:"interactive",label:"Killer.sh (exam prep)",url:"https://killer.sh/"}],
          tip:"Learn kubectl deeply before reaching for k9s or a GUI. The imperative commands and jsonpath queries will save you in production." },
        { id:"iac",      label:"Infra as Code",        type:"recommended", concepts:["state","modules","plan/apply","drift"], tools:["terraform","pulumi","opentofu"],
          description:"Infrastructure as Code makes your infrastructure reproducible, reviewable, and versioned. Terraform's plan/apply cycle is the gold standard for safe infrastructure changes.",
          resources:[{kind:"docs",label:"Terraform docs",url:"https://developer.hashicorp.com/terraform/docs"},{kind:"read",label:"OpenTofu (OSS fork)",url:"https://opentofu.org/docs/"}],
          tip:"Never run `terraform apply` without reviewing `terraform plan`. Treat IaC PRs with the same scrutiny as application code." },
        { id:"cloud",    label:"Pick a cloud",         type:"alt",         concepts:["IAM","VPC","object storage"], tools:["AWS","GCP","Azure"],
          description:"Pick one cloud and go deep before going broad. IAM, VPCs, and object storage are universal concepts — master them on one provider and they transfer.",
          tip:"Learn IAM before anything else. Misconfigured permissions cause more incidents than anything else, and understanding least-privilege prevents most of them." },
      ]},
      { id:"observe", title:"04 · Operate", color:"var(--c-pink)", items: [
        { id:"metrics",  label:"Metrics & dashboards", type:"recommended", concepts:["RED","USE","SLOs"], tools:["prometheus","grafana"],
          description:"Metrics are how you measure the health of a system. The RED method (Rate, Errors, Duration) gives you the three signals you need for every service.",
          resources:[{kind:"docs",label:"Prometheus docs",url:"https://prometheus.io/docs/"},{kind:"docs",label:"Grafana docs",url:"https://grafana.com/docs/"}],
          tip:"Learn PromQL properly — especially `rate()`, `irate()`, and `histogram_quantile()`. These three functions cover 80% of real-world alerting use cases." },
        { id:"logs",     label:"Logs & traces",        type:"recommended", concepts:["structured logs","spans","sampling"], tools:["loki","tempo","otel"],
          description:"Structured logs and distributed traces let you understand what your system is doing when it's not behaving. Use OpenTelemetry to instrument once and export anywhere.",
          resources:[{kind:"docs",label:"OpenTelemetry docs",url:"https://opentelemetry.io/docs/"},{kind:"docs",label:"Grafana Loki docs",url:"https://grafana.com/docs/loki/"}],
          tip:"Always log in JSON. Human-readable logs are great at 3am, but structured logs are queryable, filterable, and parseable by every log aggregation tool." },
        { id:"alerts",   label:"On-call & alerting",   type:"recommended", concepts:["runbooks","paging","postmortems"], tools:["pagerduty","opsgenie"],
          description:"Alerting is only valuable if alerts are actionable. Alert on symptoms, not causes — page on SLO burn rate, not on CPU spikes that nobody cares about at 3am.",
          tip:"Write a runbook for every alert before you ship it. If you can't describe what to do when the alert fires, the alert isn't ready." },
        { id:"chaos",    label:"Chaos engineering",    type:"alt",         concepts:["game days","blast radius"], tools:["litmus","gremlin"],
          description:"Chaos engineering proves your resilience claims by injecting failures deliberately. Start with game days before automating chaos experiments.",
          tip:"Start small. Chaos on a staging environment with a clear hypothesis and defined blast radius before any production experiments." },
      ]},
    ],
};
