const TRACK_DEVSECOPS = {
    id: "devsecops", code: "DEVSECOPS", title: "DevSecOps",
    tagline: "Shift security left.",
    blurb: "Bake guardrails into every pipeline stage — threat modeling, secrets, scanning, policy, supply chain.",
    storageKey: "ops4life:devsecops", accent: "var(--c-orange)",
    sections: [
      { id:"basics", title:"01 · Mental models", color:"var(--c-purple)", items: [
        { id:"threats", label:"Threat modeling",      type:"recommended", concepts:["STRIDE","trust boundaries"], tools:["pytm","owasp threat dragon"],
          description:"Threat modeling forces you to think like an attacker before writing code. STRIDE helps you systematically identify spoofing, tampering, repudiation, information disclosure, denial of service, and elevation of privilege.",
          resources:[{kind:"read",label:"OWASP Threat Modeling",url:"https://owasp.org/www-community/Threat_Modeling"},{kind:"tool",label:"OWASP Threat Dragon",url:"https://threatdragon.github.io/"}],
          tip:"Do threat modeling as a team exercise, not a solo security review. Developers know the system best — security engineers ask the uncomfortable questions." },
        { id:"appsec",  label:"AppSec fundamentals",  type:"recommended", concepts:["OWASP Top 10","auth","crypto basics"], tools:[],
          description:"The OWASP Top 10 represents the most critical web application security risks. Understanding injection, broken auth, and cryptographic failures gives you a mental model for reviewing any codebase.",
          resources:[{kind:"read",label:"OWASP Top 10",url:"https://owasp.org/www-project-top-ten/"},{kind:"interactive",label:"PortSwigger Web Security Academy",url:"https://portswigger.net/web-security"}],
          tip:"PortSwigger Web Security Academy is free and the best hands-on AppSec learning resource available. Do the labs, not just the theory." },
        { id:"netsec",  label:"Network security",     type:"alt",         concepts:["TLS","mTLS","zero trust"], tools:[],
          description:"Zero trust means never trust, always verify — even inside your perimeter. mTLS between services is the foundation of zero-trust networking.",
          tip:"Use Mozilla's SSL Config Generator for TLS configuration. It gives you battle-tested cipher suites for nginx, HAProxy, and other servers." },
      ]},
      { id:"pipeline", title:"02 · In the pipeline", color:"var(--c-teal)", items: [
        { id:"sast",    label:"SAST",                 type:"recommended", concepts:["taint analysis","false positives"], tools:["semgrep","codeql"],
          description:"Static analysis finds security bugs before code runs. Semgrep's rule-based approach lets you write custom patterns for your codebase's specific vulnerabilities.",
          resources:[{kind:"docs",label:"Semgrep docs",url:"https://semgrep.dev/docs/"},{kind:"docs",label:"CodeQL docs",url:"https://codeql.github.com/docs/"}],
          tip:"Tune false positive rates before declaring victory. A SAST tool that cries wolf on every PR will be ignored and disabled within weeks." },
        { id:"sca",     label:"Dependency scanning",  type:"recommended", concepts:["CVEs","transitive deps"], tools:["dependabot","snyk","trivy"],
          description:"Most application code is open-source dependencies. Supply chain attacks target these transitive dependencies — scanning and updating them is non-negotiable.",
          resources:[{kind:"docs",label:"Dependabot docs",url:"https://docs.github.com/en/code-security/dependabot"},{kind:"docs",label:"Trivy docs",url:"https://aquasecurity.github.io/trivy/"}],
          tip:"Enable Dependabot security updates on all repos — it automatically opens PRs for vulnerable dependencies. Review and merge them before they pile up." },
        { id:"secrets", label:"Secrets management",   type:"recommended", concepts:["rotation","KMS","short-lived creds"], tools:["vault","sops","aws secrets manager"],
          description:"Secrets in environment variables, config files, or git history are a breach waiting to happen. Use dynamic, short-lived credentials that rotate automatically.",
          resources:[{kind:"docs",label:"HashiCorp Vault docs",url:"https://developer.hashicorp.com/vault/docs"},{kind:"docs",label:"SOPS (Mozilla)",url:"https://github.com/getsops/sops"}],
          tip:"Use Vault's dynamic secrets for databases — credentials generated per-connection with short TTLs mean a leaked secret expires before it can be exploited." },
        { id:"dast",    label:"DAST & fuzzing",       type:"alt",         concepts:["crawlers","payloads"], tools:["zap","nuclei"],
          description:"Dynamic analysis tests running applications by probing them with attack payloads. DAST catches what SAST misses — runtime configuration issues, business logic flaws.",
          resources:[{kind:"docs",label:"OWASP ZAP docs",url:"https://www.zaproxy.org/docs/"},{kind:"docs",label:"Nuclei templates",url:"https://nuclei.projectdiscovery.io/"}],
          tip:"Run ZAP in baseline mode first — it catches low-hanging fruit without active scanning. Active scanning should only run against non-production environments." },
      ]},
      { id:"runtime", title:"03 · At runtime", color:"var(--c-orange)", items: [
        { id:"hardening",  label:"Container hardening", type:"recommended", concepts:["distroless","read-only fs","caps"], tools:["docker bench","trivy"],
          description:"Default container configurations are not secure. Distroless images, read-only filesystems, and dropped capabilities reduce attack surface dramatically.",
          resources:[{kind:"read",label:"Docker Bench for Security",url:"https://github.com/docker/docker-bench-security"},{kind:"docs",label:"Trivy container scanning",url:"https://aquasecurity.github.io/trivy/"}],
          tip:"Scan images at build time in CI, not just in production. Blocking vulnerable images before they're pushed is far cheaper than incident response." },
        { id:"policy",     label:"Policy as Code",      type:"recommended", concepts:["admission","guardrails"], tools:["OPA","kyverno"],
          description:"Policy as Code enforces security guardrails automatically. Kubernetes admission controllers reject non-compliant workloads before they're scheduled.",
          resources:[{kind:"docs",label:"OPA docs",url:"https://www.openpolicyagent.org/docs/"},{kind:"docs",label:"Kyverno docs",url:"https://kyverno.io/docs/"}],
          tip:"Start with audit mode before enforcement. Understanding what would be blocked before blocking it prevents surprise outages from overly strict policies." },
        { id:"sbom",       label:"Supply chain & SBOM", type:"recommended", concepts:["SLSA","provenance","sigstore"], tools:["syft","cosign"],
          description:"Software Bill of Materials lets you inventory every component in your software. Combined with Sigstore's keyless signing, you can cryptographically prove build provenance.",
          resources:[{kind:"docs",label:"Syft (SBOM generator)",url:"https://github.com/anchore/syft"},{kind:"docs",label:"Sigstore/Cosign",url:"https://docs.sigstore.dev/"}],
          tip:"Generate SBOMs at build time and attach them to release artifacts. They're useless in a security incident if you have to generate them after the fact." },
        { id:"runtimesec", label:"Runtime defense",     type:"alt",         concepts:["eBPF","syscall filtering"], tools:["falco","tetragon"],
          description:"Runtime security detects attacks in progress by monitoring syscalls and network activity. eBPF-based tools like Tetragon do this with near-zero overhead.",
          resources:[{kind:"docs",label:"Falco docs",url:"https://falco.org/docs/"},{kind:"docs",label:"Tetragon docs",url:"https://tetragon.io/docs/"}],
          tip:"Write custom Falco rules for your specific threat model, not just the default ruleset. The defaults are noisy — tune them to what actually matters in your environment." },
      ]},
    ],
};
