const TRACK_MLOPS = {
    id: "mlops", code: "MLOPS", title: "MLOps",
    tagline: "From notebook to production.",
    blurb: "Operate models like services — reproducibility, data versioning, serving, monitoring, continuous training.",
    storageKey: "ops4life:mlops", accent: "var(--c-purple)",
    sections: [
      { id:"foundation", title:"01 · Foundations", color:"var(--c-purple)", items: [
        { id:"py",    label:"Python for production", type:"recommended", concepts:["typing","packaging","async"], tools:["uv","poetry"],
          description:"Production Python is different from notebook Python. Type hints, proper packaging, and dependency management prevent the class of bugs that plague ML systems in production.",
          resources:[{kind:"docs",label:"uv (fast Python package manager)",url:"https://docs.astral.sh/uv/"},{kind:"read",label:"Python Packaging User Guide",url:"https://packaging.python.org/"}],
          tip:"Learn NumPy broadcasting well — most ML performance issues trace back to inefficient array operations that broadcasting would have eliminated." },
        { id:"envs",  label:"Reproducible envs",     type:"recommended", concepts:["lockfiles","cuda","determinism"], tools:["docker","conda","nix"],
          description:"Non-reproducible environments are ML's original sin. A model that trains differently on two machines is untestable. Lock everything: Python version, packages, CUDA version.",
          resources:[{kind:"docs",label:"Docker docs",url:"https://docs.docker.com/"},{kind:"docs",label:"NVIDIA Container Toolkit",url:"https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/"}],
          tip:"Use multi-stage Docker builds for ML images — a build stage with compilers, a runtime stage without them. Cuts image size by 60-70% and speeds up pulls." },
        { id:"data",  label:"Data fundamentals",     type:"recommended", concepts:["schemas","quality","lineage"], tools:["pandas","duckdb"],
          description:"Data quality determines model quality. Schema validation, missing value handling, and data lineage tracking are non-negotiable before any ML pipeline can be trusted.",
          resources:[{kind:"docs",label:"Great Expectations docs",url:"https://docs.greatexpectations.io/"},{kind:"docs",label:"DuckDB docs",url:"https://duckdb.org/docs/"}],
          tip:"DuckDB is excellent for local development — it queries Parquet files directly without a server. Use it to explore data before committing to a warehouse." },
      ]},
      { id:"experiment", title:"02 · Experimentation", color:"var(--c-teal)", items: [
        { id:"versioning", label:"Data versioning",      type:"recommended", concepts:["DVC","lakes","snapshots"], tools:["dvc","lakefs"],
          description:"Data versioning makes experiments reproducible. DVC integrates with Git to track data and model versions alongside code — giving you a complete snapshot of every experiment.",
          resources:[{kind:"docs",label:"DVC docs",url:"https://dvc.org/doc"},{kind:"docs",label:"LakeFS docs",url:"https://docs.lakefs.io/"}],
          tip:"DVC integrates with git — `dvc push` + `git push` together give you reproducible experiments. Tag git commits corresponding to training runs." },
        { id:"tracking",   label:"Experiment tracking",  type:"recommended", concepts:["runs","artifacts","params"], tools:["mlflow","wandb"],
          description:"Experiment tracking turns model development from art into engineering. Log every hyperparameter, metric, and artifact — you'll thank yourself when you need to reproduce a result.",
          resources:[{kind:"docs",label:"MLflow docs",url:"https://mlflow.org/docs/latest/"},{kind:"docs",label:"Weights & Biases docs",url:"https://docs.wandb.ai/"}],
          tip:"Log everything from the start, even when it feels like overhead. The experiment you didn't track will always be the one you need to reproduce." },
        { id:"features",   label:"Feature stores",       type:"alt",         concepts:["online/offline","skew"], tools:["feast","tecton"],
          description:"Feature stores solve training/serving skew — the silent killer of ML models. They ensure features computed at training time match features served at inference time.",
          resources:[{kind:"docs",label:"Feast docs",url:"https://docs.feast.dev/"}],
          tip:"Training/serving skew is often invisible until production — features computed differently at training vs inference cause model degradation that looks like data drift." },
      ]},
      { id:"production", title:"03 · Production", color:"var(--c-orange)", items: [
        { id:"serving",  label:"Model serving",            type:"recommended", concepts:["batch vs online","gpu","autoscale"], tools:["bento","triton","sagemaker"],
          description:"Model serving converts ML artifacts into reliable APIs. The choice between batch and online serving depends on latency requirements and infrastructure cost.",
          resources:[{kind:"docs",label:"BentoML docs",url:"https://docs.bentoml.com/"},{kind:"docs",label:"Triton Inference Server",url:"https://docs.nvidia.com/deeplearning/triton-inference-server/"}],
          tip:"Profile your model's latency and memory footprint before choosing a serving framework. A framework optimized for computer vision may be wrong for NLP." },
        { id:"monitor",  label:"Monitor drift & quality",  type:"recommended", concepts:["data drift","perf","feedback loops"], tools:["evidently","whylabs"],
          description:"Models degrade silently. Data drift — when production data drifts from training data — causes model performance to decay in ways that don't show up in infrastructure metrics.",
          resources:[{kind:"docs",label:"Evidently AI docs",url:"https://docs.evidentlyai.com/"}],
          tip:"Set up data drift monitoring before you need it. By the time you notice model degradation in business metrics, you've already served bad predictions to real users." },
        { id:"ct",       label:"Continuous training",      type:"recommended", concepts:["pipelines","triggers"], tools:["kubeflow","airflow"],
          description:"Continuous training keeps models current as data evolves. Automated retraining pipelines triggered by data drift or scheduled intervals replace manual model updates.",
          resources:[{kind:"docs",label:"Kubeflow Pipelines docs",url:"https://www.kubeflow.org/docs/components/pipelines/"},{kind:"docs",label:"Apache Airflow docs",url:"https://airflow.apache.org/docs/"}],
          tip:"Design pipelines to be idempotent — running them twice should produce the same result. This makes debugging failed runs much easier." },
        { id:"llmops",   label:"LLM evals",                type:"alt",         concepts:["golden sets","judges"], tools:["ragas","promptfoo"],
          description:"LLM evaluation requires different methods than traditional ML. Golden test sets and LLM-as-judge approaches let you measure quality without hand-labeling every output.",
          resources:[{kind:"docs",label:"RAGAS docs",url:"https://docs.ragas.io/"},{kind:"docs",label:"promptfoo docs",url:"https://www.promptfoo.dev/docs/"}],
          tip:"Build your golden test set from real production queries, not synthetic examples. Real edge cases are always weirder than anything you'd generate." },
      ]},
    ],
};
